### PR TITLE
Fixed toast message display in fragment

### LINKED ISSUE #76: [Bug] Missing warning message when selecting an invalid section
**Current**: When selecting a a voting section, the user selects a county and completes an invalid polling section number. When the user taps the`Continue` button, nothing happens.

**Expected**: When selecting a a voting section, the user selects a county and completes an invalid polling section number When the user taps the`Continue` button, **a toast with a message error should appear.** 

This doesn't work fine because the message event is triggered in the `parentViewModel` which is attached to the `activity` so the solution would be to listen to the error in the `BaseActivity`

### PR DESCRIPTION
**Pull request by sergiuciuperca**
Closes #76 

Fixes also a bug when the user closes the application before completing section configuration (when the app is opened again it is redirected to Forms that expects a section to be set)

### CODE REVIEW

File: app/src/main/java/ro/code4/monitorizarevot/ui/splashscreen/SplashScreenActivity.kt [hunk 1]
```diff
@@ -18,12 +19,15 @@ class SplashScreenActivity: BaseActivity<SplashScreenViewModel>() {
...
+        viewModel.loginLiveData().observe(this, Observer { loginStatus ->
+            val activity: Class<*> = if (loginStatus.isLoggedIn) {
+                if (loginStatus.isBranchConfigCompleted) {
+                    MainActivity::class.java
+                } else {
+                    BranchActivity::class.java
+                }
             } else {
-                activity = LoginActivity::class.java
+                LoginActivity::class.java
```
Comment (AlexandraDaraban) [inline app/src/main/java/ro/code4/monitorizarevot/ui/splashscreen/SplashScreenActivity.kt]: You could use a `when` expression with multiple conditions instead of `if else`

**Review by AlexandraDaraban — CHANGES_REQUESTED** [review]
Hey, @sergiuciuperca! The PR looks good but there is a issue that I would like you to look into. Thanks 😄

**Comment by sergiuciuperca** [comment]
Hi, @AlexandraDaraban, Pushed a commit to fix it :)

**Comment by AlexandraDaraban** [comment]
@sergiuciuperca , could you please solve the conflicts before merging?

**Comment by sergiuciuperca** [comment]
@AlexandraDaraban Merged.

Also removed BrachActivity from  Back Stack when navigating to MainActivity.

**Review by AlexandraDaraban — APPROVED** [review]
Looks good!
